language: python
python:
- '2.6'
- '2.7'
- '3.4'
- '3.5'
- pypy
install:
- pip install -U pip wheel tox-travis
script: tox
deploy:
  provider: pypi
  user: figo
  password:
    secure: RnjoyK822dVuT4vo3sA2nvqJVX3H6OJeHA6wtkm0rQ8YacCagIEKYzIJaoBdVi2AZsn6UAsi1AyVotSHkrk/7AVl4PG0jRGP290YOajWn+sEdJRuPqLQWknoEMuA44XuxwIIfh93beGU4dgZWnJ5vjgKFImLiKCONvm7CRtXCfs=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: '3.5'
    all_branches: true
